
### 1. Create a user with a valid email
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Faida",
  "username": "faida@example.com",
  "password": "example123"
}

### 2. List all users
GET http://localhost:3000/api/users

### 3. Get one user by ID
GET http://localhost:3000/api/users/1

### 4. Update a user's name using their email username
PUT http://localhost:3000/api/users/faida@example.com
Content-Type: application/json

{
  "name": "Faida Kulimushi"
}

### 5. Test invalid email (should return 400)
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Test User",
  "username": "not-an-email",
  "password": "example123"
}

### 6. Test duplicate email (run after request 1 succeeds)
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Another User",
  "username": "faida@example.com",
  "password": "example456"
}



### Exercise 10: Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "faida@example.com",
  "password": "secret"
}



### Exercise 10: Create a blog as a logged-in user
POST http://localhost:3000/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhaWRhQGV4YW1wbGUuY29tIiwiaWQiOjIsImlhdCI6MTc5MTU1MzE5Nn0.SFL8vCLz32s-zRSl41UKmhX5GdBZNXBoed-_S7p3Fc8
Content-Type: application/json

{
  "title": "Learning Full Stack Open",
  "author": "Faida",
  "url": "https://fullstackopen.com/",
  "likes": 0
}